# Generated by Django 5.2.1 on 2025-07-26 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IDCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=20, unique=True)),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        unique=True,
                        verbose_name="Student ID",
                    ),
                ),
                (
                    "college",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="College/School",
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Course"
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Year/Batch"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        verbose_name="Contact Number",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="id_cards/"),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="id_cards/qr_codes/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_card",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
