# Generated by Django 5.2.1 on 2025-08-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("idcard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="idcard",
            old_name="card_number",
            new_name="Full_Name",
        ),
    ]
