# Generated by Django 5.2.1 on 2025-08-06 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idcard", "0002_rename_card_number_idcard_full_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="idcard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
