# Generated by Django 5.2.1 on 2025-07-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("designation", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("join_date", models.DateField()),
                ("profile_image", models.ImageField(upload_to="employee_photos/")),
                ("qr_code", models.ImageField(blank=True, upload_to="employee_qr/")),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employeeid_employee",
            },
        ),
    ]
