# Generated by Django 5.2.1 on 2025-09-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackform",
            name="owner_email",
            field=models.EmailField(
                default=1,
                help_text="Email where you want to receive feedback notifications",
                max_length=254,
                verbose_name="Form Owner Email",
            ),
            preserve_default=False,
        ),
    ]
