# Generated by Django 5.2.1 on 2025-08-21 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Kisan ka Naam (Name)"
                    ),
                ),
                (
                    "village",
                    models.CharField(max_length=100, verbose_name="Gaav (Village)"),
                ),
                (
                    "phone",
                    models.CharField(max_length=15, verbose_name="Mobile Number"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "khet_area",
                    models.FloatField(
                        help_text="Khet ka area (acres mein)",
                        verbose_name="Khet ka Area",
                    ),
                ),
                (
                    "phasal_name",
                    models.CharField(
                        max_length=100, verbose_name="Phasal ka Naam (Crop)"
                    ),
                ),
                (
                    "bowaai_date",
                    models.DateField(verbose_name="Bone ki Date (Sowing Date)"),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farm.farmer",
                        verbose_name="Kisan (Farmer)",
                    ),
                ),
            ],
        ),
    ]
