# Generated by Django 5.2.1 on 2025-08-22 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("rain", "बारिश (Rain)"),
                            ("storm", "तूफान (Storm)"),
                            ("hail", "ओलावृष्टि (Hailstorm)"),
                            ("drought", "सूखा (Drought)"),
                            ("heatwave", "लू (Heatwave)"),
                            ("other", "अन्य (Other)"),
                        ],
                        max_length=20,
                        verbose_name="अलर्ट प्रकार (Alert Type)",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="शीर्षक (Title)"),
                ),
                ("description", models.TextField(verbose_name="विवरण (Description)")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "कम (Low)"),
                            ("medium", "मध्यम (Medium)"),
                            ("high", "उच्च (High)"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="गंभीरता (Severity)",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="प्रभावी तिथि (Valid From)",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="समाप्ति तिथि (Valid Until)"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="All Regions",
                        max_length=100,
                        verbose_name="स्थान (Location)",
                    ),
                ),
            ],
            options={
                "verbose_name": "मौसम चेतावनी (Weather Alert)",
                "verbose_name_plural": "मौसम चेतावनियाँ (Weather Alerts)",
                "ordering": ["-valid_from"],
            },
        ),
    ]
