# Generated by Django 5.2.1 on 2025-08-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_assist", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hospital",
            options={
                "ordering": ["name"],
                "verbose_name": "Hospital",
                "verbose_name_plural": "Hospitals",
            },
        ),
        migrations.AddField(
            model_name="hospital",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="district",
            field=models.CharField(
                default="Sultanpur", max_length=100, verbose_name="District"
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="is_24x7",
            field=models.BooleanField(default=False, verbose_name="24x7 Available"),
        ),
        migrations.AddField(
            model_name="hospital",
            name="state",
            field=models.CharField(
                default="Uttar Pradesh", max_length=100, verbose_name="State"
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Full Address"),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Hospital Name"),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="Phone Number"),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(fields=["name"], name="health_assi_name_d853a7_idx"),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(fields=["state"], name="health_assi_state_99fc44_idx"),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(
                fields=["district"], name="health_assi_distric_84f03d_idx"
            ),
        ),
    ]
