# Generated by Django 5.2.1 on 2025-09-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_no', models.CharField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('digital_signature', models.ImageField(upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'political_id_idcard',
            },
        ),
    ]
