# Generated by Django 5.2.1 on 2025-08-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_alter_resume_options_alter_resume_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="address",
            field=models.TextField(
                blank=True, help_text="Your full address", null=True
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="job_title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Job Title/Position"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="location",
            field=models.CharField(
                blank=True, help_text="City, Country", max_length=100, null=True
            ),
        ),
    ]
